/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and obtain a JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Bad credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too many failed attempts; retry after the Retry-After header */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new access token
         * @description The refresh token is rotated: the presented one stops working and the response carries its replacement. Public, because an expired access token must not be needed to renew a session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Renewed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Refresh token unknown, expired, already used, or the account can no longer sign in */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Access tokens are stateless and simply expire; this stops the session being renewed. Always 204, whether or not the token existed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hosts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            data?: components["schemas"]["Host"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a host */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["HostInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Host"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a host */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Host */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Host"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a host
         * @description Omit `sshKey` to keep the stored key unchanged.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["HostInput"];
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Host"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete a host
         * @description Also deletes every database on this host, their backup history and every stored archive. Read `databaseCount` and `backupCount` from the host first and confirm with the user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List databases */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Databases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            data?: components["schemas"]["Database"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a database */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["DatabaseInput"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Database"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a database */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Database */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Database"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a database
         * @description Omit `password` to keep the stored password unchanged.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["DatabaseInput"];
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Database"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /**
         * Delete a database
         * @description Also deletes its backup history, every stored archive and its retention policy. Read `backupCount` from the database first and confirm with the user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{id}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a backup of this database now
         * @description The backup runs asynchronously; the queue is drained about once a minute.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backup queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["QueuedBackup"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{databaseId}/retention-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        /** Get the database's retention policy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    databaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retention policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["RetentionPolicy"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Create or replace the database's retention policy */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    databaseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RetentionPolicyInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["RetentionPolicy"];
                        };
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["RetentionPolicy"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        /** Delete the database's retention policy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    databaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List backups */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Filters by database name (friendly name or database name) */
                    search?: string;
                    sort?: "createdAt" | "executedAt" | "state" | "size" | "success" | "name";
                    order?: "asc" | "desc";
                    databaseId?: string;
                    /** @description Only backups of databases on this host */
                    hostId?: string;
                    /** @description Only backups in this state */
                    state?: components["schemas"]["BackupState"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backups */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            data?: components["schemas"]["Backup"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a backup with its captured command output */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backup */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BackupDetail"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a backup (record and stored file) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{id}/download-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a single-use download ticket
         * @description A browser navigation cannot send an Authorization header, so downloading through `fetch` means holding the whole archive in memory. Request a ticket here, then point a link at `/api/v1/backups/{id}/download?token=…` and let the browser stream it to disk. The ticket is valid once and expires within seconds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                token?: string;
                                /** @description Seconds until the ticket expires */
                                expiresIn?: number;
                                filename?: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /**
         * Download the stored backup archive
         * @description Authorized either by a bearer token or by a single-use `token` from the download-ticket endpoint.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Single-use download ticket; required when no bearer token is sent */
                    token?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Zip archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                /** @description Backup file could not be read from storage */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated statistics for the dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["DashboardStats"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's API keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ApiKey"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create an API key
         * @description The response contains the plaintext key exactly once; store it now.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        comment?: string | null;
                        /** Format: date-time */
                        validUntil?: string | null;
                        /** @description Databases this key may trigger backups for. Omit or send an empty list for a key that can back up every database. */
                        databaseIds?: string[] | null;
                    };
                };
            };
            responses: {
                /** @description Created — `key` holds the one-time plaintext key */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CreatedApiKey"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an API key
         * @description Only the user who created a key may delete it.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the current user's password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        passwordOld: string;
                        /** Format: password */
                        passwordNew: string;
                        /** Format: password */
                        passwordNewConfirm: string;
                    };
                };
            };
            responses: {
                /** @description Password changed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            data?: components["schemas"]["User"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                        roles?: string[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** Get a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a user
         * @description Omit `password` to keep it unchanged. `authorities` replaces the user's role set.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password?: string | null;
                        enabled?: boolean;
                        authorities?: string[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/create/{databaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                databaseId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a backup (machine-to-machine)
         * @description Legacy-compatible endpoint authenticated with an `X-API-Key` header
         *     instead of a JWT. Kept verbatim from Pneumatik 1.x.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    databaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backup queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["QueuedBackup"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: {
                        code?: string;
                        message?: string;
                    }[];
                } | null;
            };
        };
        PaginatedEnvelope: {
            meta?: {
                page?: number;
                pageSize?: number;
                /** Format: int64 */
                total?: number;
                /** Format: int64 */
                filtered?: number | null;
            };
        };
        LoginResponse: {
            username?: string;
            roles?: string[];
            token_type?: string;
            access_token?: string;
            expires_in?: number;
            refresh_token?: string;
        };
        /** @enum {string} */
        StorageProvider: "DIRECT" | "S3";
        /** @enum {string} */
        Trigger: "TRIGGER_HOURLY" | "TRIGGER_4HOURLY" | "TRIGGER_12HOURLY" | "TRIGGER_DAILY" | "TRIGGER_MANUAL";
        /** @enum {string|null} */
        DatabaseType: "MYSQL" | "POSTGRESQL" | null;
        /** @enum {string|null} */
        BackupState: "CREATED" | "RUNNING" | "FINISHED" | "FAILED" | null;
        Host: {
            /** Format: uuid */
            id?: string;
            friendlyName?: string | null;
            /** @description friendlyName if set, else hostname */
            name?: string;
            hostname?: string;
            port?: number;
            sshHostname?: string | null;
            sshUser?: string | null;
            sshPort?: number | null;
            hasSshKey?: boolean;
            useSSL?: boolean;
            /** @description whether the SSH host key must match hostKey */
            verifyHostKey?: boolean;
            /** @description pinned host key in known_hosts format; null until the first verified connection */
            hostKey?: string | null;
            /**
             * Format: int64
             * @description databases on this host; what a delete would take with it
             */
            databaseCount?: number;
            /** @description names of those databases (detail view only) */
            databaseNames?: string[];
            /**
             * Format: int64
             * @description backups across those databases (detail view only)
             */
            backupCount?: number;
        };
        Database: {
            /** Format: uuid */
            id?: string;
            friendlyName?: string | null;
            /** @description friendlyName if set, else databaseName */
            name?: string;
            databaseName?: string;
            /** Format: uuid */
            hostId?: string;
            hostName?: string;
            user?: string | null;
            hasPassword?: boolean;
            storageProvider?: components["schemas"]["StorageProvider"];
            trigger?: components["schemas"]["Trigger"];
            databaseType?: components["schemas"]["DatabaseType"];
            /**
             * Format: int64
             * @description backups of this database; what a delete would take with it
             */
            backupCount?: number;
            /**
             * Format: int64
             * @description of those, how many still have a stored archive (detail view only)
             */
            storedFileCount?: number;
        };
        Backup: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            databaseId?: string;
            databaseName?: string;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            executedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /**
             * Format: int64
             * @description run duration in milliseconds (finishedAt - executedAt)
             */
            durationMs?: number | null;
            filename?: string | null;
            /** @description human-readable, e.g. "12.5 MB" */
            size?: string | null;
            /**
             * Format: int64
             * @description size of the uncompressed dump
             */
            rawSizeBytes?: number | null;
            /**
             * Format: int64
             * @description size of the stored zip archive
             */
            archivedSizeBytes?: number | null;
            /** @description whether the stored archive is AES-256-GCM encrypted */
            encrypted?: boolean;
            state?: components["schemas"]["BackupState"];
            exitCode?: number | null;
            success?: boolean;
            storageProvider?: components["schemas"]["StorageProvider"];
            /** @description username; null for scheduled backups */
            createdBy?: string | null;
            /** @description set for scheduled backups instead of createdBy */
            trigger?: string | null;
        };
        BackupDetail: components["schemas"]["Backup"] & {
            /** @description captured output of the dump command; check this when a backup failed */
            output?: string | null;
        };
        QueuedBackup: {
            queued?: boolean;
            /** Format: uuid */
            databaseId?: string;
        };
        ApiKey: {
            /** Format: uuid */
            id?: string;
            /** @description first characters of the key */
            keyHint?: string | null;
            comment?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            validUntil?: string | null;
            /** Format: date-time */
            lastConnectedAt?: string | null;
            isValid?: boolean;
            createdBy?: string;
            /** @description databases this key may back up; empty means all of them */
            databaseIds?: string[];
            /** @description names of those databases, for display */
            databaseNames?: string[];
        };
        CreatedApiKey: components["schemas"]["ApiKey"] & {
            /** @description plaintext key — shown exactly once */
            key?: string;
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            /** Format: email */
            email?: string;
            enabled?: boolean;
            roles?: string[];
        };
        RetentionPolicy: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            databaseId?: string;
            keepCount?: number | null;
            keepDays?: number | null;
            enabled?: boolean;
        };
        DashboardStats: {
            totals: {
                /** Format: int64 */
                databases: number;
                /** Format: int64 */
                hosts: number;
                /** Format: int64 */
                backups: number;
                /**
                 * Format: int64
                 * @description total storage used by all backups
                 */
                storageBytes: number;
                /** Format: int64 */
                failedLast7Days: number;
                /**
                 * Format: int64
                 * @description databases overdue for a successful backup
                 */
                staleDatabases?: number;
            };
            /** @description Per-database aggregates, ordered by storage descending */
            databases: components["schemas"]["DatabaseStats"][];
            /** @description Scheduled databases whose last successful backup is older than twice their schedule interval (or that never had one), worst first. A failure count alone misses these — a database whose backups silently stopped reports no failures at all. */
            stale?: components["schemas"]["DatabaseStats"][];
            /** @description One entry per day for the last 14 days, oldest first */
            activity: components["schemas"]["ActivityDay"][];
        };
        DatabaseStats: {
            /** Format: uuid */
            databaseId: string;
            databaseName: string;
            /** Format: int64 */
            backupCount: number;
            /** Format: int64 */
            storageBytes: number;
            /** Format: date-time */
            lastBackupAt?: string | null;
            /**
             * Format: date-time
             * @description null when no backup of this database ever succeeded
             */
            lastSuccessfulBackupAt?: string | null;
            trigger?: components["schemas"]["Trigger"];
            /** @description overdue for a successful backup */
            isStale?: boolean;
            /** @description whole days since the last successful backup; null when there never was one */
            staleSinceDays?: number | null;
        };
        ActivityDay: {
            /**
             * Format: date
             * @description calendar day, server timezone
             */
            date: string;
            /** Format: int64 */
            finished: number;
            /** Format: int64 */
            failed: number;
            /**
             * Format: int64
             * @description all backups created that day, any state
             */
            total: number;
        };
        RetentionPolicyInput: {
            /** @description keep at most the N most recent successful backups */
            keepCount?: number | null;
            /** @description delete successful backups older than N days */
            keepDays?: number | null;
            /** @default true */
            enabled: boolean;
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Invalid request parameter */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request conflicts with resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Validation failed; `error.fields` maps field names to errors */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        id: string;
        page: number;
        pageSize: number;
    };
    requestBodies: {
        HostInput: {
            content: {
                "application/json": {
                    friendlyName?: string | null;
                    hostname: string;
                    /** @description defaults to 3306 */
                    port?: number | null;
                    sshHostname?: string | null;
                    sshUser?: string | null;
                    sshPort?: number | null;
                    /** @description SSH private key; stored encrypted, never returned */
                    sshKey?: string | null;
                    useSSL?: boolean | null;
                    /** @description Verify the SSH host key. Without it, anything that can answer for the hostname receives the database password. */
                    verifyHostKey?: boolean | null;
                    /** @description Pinned host key in known_hosts format. Leave empty to pin whatever the first verified connection sees; send an empty string to forget the pin and re-learn it. */
                    hostKey?: string | null;
                };
            };
        };
        DatabaseInput: {
            content: {
                "application/json": {
                    friendlyName?: string | null;
                    databaseName: string;
                    /** Format: uuid */
                    hostId: string;
                    user?: string | null;
                    /**
                     * Format: password
                     * @description stored encrypted, never returned
                     */
                    password?: string | null;
                    storageProvider: components["schemas"]["StorageProvider"];
                    trigger: components["schemas"]["Trigger"];
                    databaseType?: components["schemas"]["DatabaseType"];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
